### PR TITLE
Godot 4 theme changes

### PR DESCRIPTION
**Pull request by Kregap**
Addresses #45.
⚠️ **Tested only on Windows.** ⚠️

I tried to keep out of the code, but when after moving nodes around in tree signals or references in general broke I adjusted there. Otherwise some layout changes required a bit of code. The other bigger changes I described below.

### Gitignore changes
3b302082066d62e3a7f8b71dca11fe0c4f3c9e42, 73aae3a86e9d80d46b7b963c574e0f572a7d203f
AFAIK you should keep `/.godot ` file ignored, everyone has different editor setup and we shouldn't force our configuration on each other. As examplified in [Godo Demo repo](https://github.com/godotengine/godot-demo-projects/blob/master/.gitignore).
I added it to `.gitignore` and removed already exiting `.godot` ditrectory from repo.

### File load popup error
56f91d2d6bbbcff19b9e22ae43fad9da0b71cf15
Not sure if that was a proper fix, but generally I couldn't access file selection popup, so had to do something to work on the style there. Please verify that.

### Theme changes.
0768bf2779a9ba6b72750b2998198214bf449bce
I copied some colors, but some adjusted based on personal preferences. You can find many changes I'll explain reasoning for the bigger ones.
#### Version selection
I think because Mono is switching all versions to that and then you select Stable, RC, etc. in either mono or standard variant it makes sense to suggest that in UI instead of mixing it with the other checkboxes.
#### Add new popup
Changed from Popup to Panel, cause I couldn't figure out how make popup persist (not hide) when you click outside of it, or if you click back in the app after drag'n'dropping `godot.project` file from you file explorer and adjusted code accordingly to still work.
Changed layout to be more orderly and to make button be visually grouped with associated with them text boxes.
Added Prettify button with some simple logic to pretty-print multiple arguments if one specifies multiple of them. It breaks them into lines and creates pairs if it makes sense (e.g. pairs `--path` with `C://path/to/project`, but won't pair `-silent` with `-debug`) It's run only on demand. When saving the project now raw text is saved in `raw_arguments` - only used to display text in Add new form and in `arguments` where new lines are replaced with spaces to avoid problems when running those project commands.

Godot_v4 3-dev6_win64_lUM1lWz0FJ
Godot_v4 3-dev6_win64_kWm0FbbRAK
Godot_v4 3-dev6_win64_qedPRAbusy
Godot_v4 3-dev6_win64_vnYKthcZPH

### CODE REVIEW

**Comment by noidexe** [comment]
Thanks. Overall I think it's an amazing change. I like what you did with the mono toggle and the rest of the version tags. It's a nice improvement to UX. A couple things that could be further improved if you can:

- While we're at it let's just change "Mono" to "C# Support". I think it's more intuitive and the official website doesn't show it as "mono" anymore either. 

- I know it's subjective but I feel the dark borders make every button and panel fight for attention. I don't mind it for hover or focus but I think it should be subtler for normal style


> When saving the project now raw text is saved in raw_arguments - only used to display text in Add new form and in arguments where new lines are replaced with spaces to avoid problems when running those project commands.

This is throwing an error
image
I think doing `line_edit_arguments.text = entry.get("arguments_raw", entry.arguments)` will be enough to fix it

I'll let you know if I notice anything else. Thanks again for the great work

**Comment by Kregap** [comment]
Forgot about dark theme requirement. Added in last commit. Looks as shown below.
Godot_v4 3-dev6_win64_FQ2ZV2XH3c

**Comment by Kregap** [comment]
I added `ThemeUpdater` scene. You can copy folder with a theme, then load `main.tres` into this scene `Theme` exported variable change font colors then trigger update with `Trigger Update` export checkbox.
Godot_v4 3-dev6_win64_R9qDtbKdSZ
I didn't want to complicate it more with applying changes to styleboxes too. So I just extracted reused Styleboxes into their files and they need to be adjusted there and when creating new theme attached to that theme file.

----

Additionally all styleboxes now are attached to `main` theme even the variants, by theme variants (e.g. look at `ButtonRed`).

**Comment by Kregap** [comment]
Sorry just saw your last comment, will work on those points tomorrow. I agree with all of them and will implement the required changes/fixes.

**Comment by Kregap** [comment]
Comments were addressed as suggested.

**Comment by noidexe** [comment]
I fixed an error when an old config didn't have a theme entry but other than that it looks great.

Merged. Thanks for contributing!

**Comment by noidexe** [comment]
Closes #45

**Pull request merged**
